import java.awt.Component;
import java.awt.Dimension;
import java.beans.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

public class UsingBeans extends JFrame {

    /**
     * Creates new form UsingBeans
     */
    public UsingBeans() {
        try{
            initComponents();
        }
        catch(Exception e){}
        
        ziarenkoTerminarz1.addPropertyChangeListener(new PropertyChangeListener(){
            @Override
            public void propertyChange(PropertyChangeEvent e){
                if(e.getPropertyName().equals("rozmiarPola")){
                    Component[] comps = ziarenkoTerminarz1.getComponents();
                    JScrollPane scr = (JScrollPane) comps[1];
                    scr.setMaximumSize(new Dimension(98,(Integer)e.getNewValue()));
                    ziarenkoTerminarz1.revalidate();
                    ziarenkoTerminarz1.repaint();
                }
                else if(e.getPropertyName().equals("ramyCzasowe")){ }
            }
        });
        
        ziarenkoTerminarz1.addVetoableChangeListener(new VetoableChangeListener(){
            @Override
            public void vetoableChange(PropertyChangeEvent e) throws PropertyVetoException{
                if(e.getPropertyName().equals("ramyCzasowe")){
                    Component[] comps = ziarenkoTerminarz1.getComponents();
                    JTextField txf1 = (JTextField) comps[7];
                    JTextField txf2 = (JTextField) comps[8];
                    DateFormat df2 = new SimpleDateFormat("dd/MM/yyyy");
                    Date date1, date2;
                    try {
                        date1 = df2.parse(txf1.getText());
                        date2 = df2.parse(txf2.getText());
                        if(date1.after(date2)){
                            throw new PropertyVetoException("Data poczatkowa pozniejsza niz data koncowa", e);
                        }
                    } 
                    catch (ParseException ex) {
                        Logger.getLogger(UsingBeans.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
        Component[] comps = ziarenkoTerminarz1.getComponents();
        JScrollPane scr = (JScrollPane) comps[1];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ziarenkoTerminarz1 = new ZiarenkoTerminarz();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        try {
            ziarenkoTerminarz1.setRamyCzasowe(new String[] {"25/03/2018", "31/03/2018"});
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        ziarenkoTerminarz1.setRozmiarPola(100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ziarenkoTerminarz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ziarenkoTerminarz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsingBeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsingBeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsingBeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsingBeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UsingBeans().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ZiarenkoTerminarz ziarenkoTerminarz1;
    // End of variables declaration//GEN-END:variables
}
